apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: guestbook-prod
    repoURL: git@github.com:niki130396/argocd-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true